version: '3.8'

services:
  app:
    build: .
    container_name: express-ts
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev